apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ticket-booking
  labels:
    app: ticket-booking-system
    component: frontend
  annotations:
    description: "Frontend Web Service"
spec:
  type: LoadBalancer
  selector:
    app: ticket-booking-system
    component: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: None
